apiVersion: v1
kind: Service
metadata:
  name: fa-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: flask-app
    app.kubernetes.io/name: flask-kubernetes-helm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30088
